global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
